---
apiVersion: v1
kind: Namespace
metadata:
  name: phpmyadmin
  labels:
    name: phpmyadmin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
  namespace: phpmyadmin
data:
  config.user.inc.php: |
    <?php
    // Конфигурация будет переопределена переменными окружения
    // phpMyAdmin автоматически использует PMA_HOST, PMA_PORT, etc.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: cr.yandex/crpq0u0820d6gn43id60/phpmyadmin:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PMA_HOST
          value: ""
        - name: PMA_PORT
          value: ""
        - name: PMA_USER
          value: ""
        - name: PMA_PASSWORD
          value: ""
        - name: UPLOAD_LIMIT
          value: "300M"
        - name: MEMORY_LIMIT
          value: "256M"
        - name: PMA_ARBITRARY
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/phpmyadmin/config.user.inc.php
          subPath: config.user.inc.php
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: phpmyadmin-config

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: http
